Adds manage script for packaging application in containers
bcgov/orgbook-bc-client-angular pull request #5
Opened 2021-02-21 23:35 UTC by amanji

Signed-off-by: Akiff Manji <akiff.manji@gmail.com>

2021-02-22 00:16 UTC, amanji commented
Need to add usage instructions

2021-02-22 14:07 UTC, WadeBarnes commented
Looking good

2021-02-23 16:33 UTC, WadeBarnes requested changes
See; https://github.com/bcgov/aries-vcr-client/pull/6#pullrequestreview-596539144

2021-02-23 17:29 UTC, WadeBarnes commented
The application is connecting to `https://dev.orgbook.gov.bc.ca` rather then connecting to the locally running instance of `aries-vcr`.

2021-02-23 19:48 UTC, esune requested changes
Added a couple of tweaks/recommendations.

2021-02-23 19:48 UTC, esune commented on docker/docker-compose.yml
> +  vcr:
If you need to refer to the existing network created by `aries-vcr`, I believe you need to explicitly define it as external ot the project will create a new one named this way with a different prefix. See [here](https://github.com/esune/aries-vcr-issuer-agency/blob/main/docker/docker-compose.yml#L127-L129) as an example.

2021-02-23 19:48 UTC, esune commented on docker/manage
> +  export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-vcr}"
Might want to rename the default compose project name to `vcr-web` to avoid clashing with the existing `vcr` one?

2021-02-23 19:48 UTC, esune commented on docker/manage
> +deleteVolumes() {
This is a bit misleading, as the function call will actually result in the removal of all containers, networks AND volumes - not just the latter.

2021-02-24 01:45 UTC, amanji commented on docker/docker-compose.yml
> +  vcr:
Done, thanks!

2021-02-24 14:44 UTC, amanji commented on docker/manage
> +  export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-vcr}"
Changed to `vcr-web`

2021-02-24 14:45 UTC, amanji commented on docker/manage
> +deleteVolumes() {
How about `cleanup()` ?

2021-02-24 17:34 UTC, WadeBarnes requested changes
See comments here; https://github.com/bcgov/aries-vcr-client/pull/6#pullrequestreview-597719283

2021-02-24 22:36 UTC, WadeBarnes approved these changes

2021-02-24 22:38 UTC, esune approved these changes

2021-02-24 22:38 UTC, merged